name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          ### Welcome to the Data Analysis Scripts Repository! 👋

          Thank you for opening your first issue! We are thrilled to have you here. This repository is dedicated to collecting useful data analysis scripts in Python, R, and SQL. Your contributions and ideas are greatly appreciated.

          Please make sure to provide as much detail as possible in your issue to help us understand and address it effectively. If you haven't already, take a look at our [README](https://github.com/your-username/data-analysis-scripts/blob/main/README.md) and [CONTRIBUTING](https://github.com/your-username/data-analysis-scripts/blob/main/CONTRIBUTING.md) guidelines.

          We look forward to collaborating with you! 🚀

        pr-message: >
          ### Welcome to the Data Analysis Scripts Repository! 👋

          Thank you for submitting your first pull request! We are excited to see your contribution. This repository is dedicated to collecting useful data analysis scripts in Python, R, and SQL. Your efforts in enhancing this repository are highly valued.

          Please ensure that your pull request is well-documented and follows our coding standards. For more information, you can check out our [README](https://github.com/your-username/data-analysis-scripts/blob/main/README.md) and [CONTRIBUTING](https://github.com/your-username/data-analysis-scripts/blob/main/CONTRIBUTING.md) guidelines.

          We appreciate your contribution and look forward to working together! 🚀
